version: '2'
services:
  rcgech:
    build:
      context: ./horodateur_api
      dockerfile: Dockerfile_dev
    environment:
      - WS_URI=http://nginx.horodateur:8080
      - PRIVATE_KEY=87ED42E2AFCF878D1DAA2183AA23F32023F31D377D431BD005207A24B2ACD93A
      - DB_DSN=host=postgres user=tsUhfmkMfY dbname=rcgehorodatage sslmode=disable password=lrwOuiz4gH
      - LOCKED_ADDR=0x88AB30749e745A66262275e0489373D3E0781E74
      - ERROR_THRESHOLD=0.1
      - WARNING_THRESHOLD=1
    links:
      - postgres
    command: bash -c "go get github.com/pilu/fresh && fresh"
    depends_on:
      - nginx.horodateur
    volumes:
      - ./horodateur_api:/go/src/github.com/geneva_horodateur/
    ports:
      - "0.0.0.0:8090:8090"

  webapp:
    build:
      context: ./horodateur_webapp
    ports:
      - "0.0.0.0:8001:8080"
    environment:
      - KEY_NAME=myservice # The .cert and .key must have the same name
      - IDP_METADATA=http://ec2-18-184-234-216.eu-central-1.compute.amazonaws.com/ssorec.geneveid.ch_dgsi_blockchain.xml #Public URL where IdP can be found
      - SP_URL=http://ec2-18-184-234-216.eu-central-1.compute.amazonaws.com:8001 # URL of the service provider
      - API_HOST=rcgech:8090 # API host, is equal to the <api container name>:<port>
    working_dir: /app
    command: /app/webapp
    volumes:
      - "./myservice.cert:/app/myservice.cert"
      - "./myservice.key:/app/myservice.key"

  postgres:
    image: postgres:9.5
    environment:
      - POSTGRES_USER=tsUhfmkMfY
      - POSTGRES_PASSWORD=lrwOuiz4gH
      - POSTGRES_DB=rcgehorodatage
  nginx.horodateur:
    image: nginx
    container_name: nginx.horodateur
    ports:
      - 8080:8080
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
