version: '2'
services:
  rcgech:
    build: .
    environment:
      - WS_URI=https://rinkeby.infura.io/v3/afeacc980c634655875d915ed65cb0e4
      - PRIVATE_KEY=63007E20C822A425B0A7B0C9FF2E2AD54BE313DCE9BCEC6963412021F8F2D2D7
      - DB_DSN=host=postgres user=tsUhfmkMfY dbname=rcgehorodatage sslmode=disable password=lrwOuiz4gH
      - LOCKED_ADDR=0x3ab05401c0d9483dbeb108b741248bb8e82e323d
      - ERROR_THRESHOLD=0.1
      - WARNING_THRESHOLD=1
    links:
      - postgres

  caddy-rev:
    image: abiosoft/caddy
    ports:
      - "0.0.0.0:8001:80"
      - "0.0.0.0:8443:443"
    volumes:
      - "./Caddyfile:/etc/Caddyfile:ro"
      - "./mockup:/var/www:ro"

  postgres:
    image: postgres:9.5
    environment:
      - POSTGRES_USER=tsUhfmkMfY
      - POSTGRES_PASSWORD=lrwOuiz4gH
      - POSTGRES_DB=rcgehorodatage
