version: '2'
services:
  rcgech:
    build: ./horodateur_api
    environment:
      - WS_URI=https://rinkeby.infura.io/v3/afeacc980c634655875d915ed65cb0e4
      - PRIVATE_KEY=18030537DBDD38D0764947D40BED98FC4D2A21AF82765A7DE7B13D2E4076773C
      - DB_DSN=host=postgres user=tsUhfmkMfY dbname=rcgehorodatage sslmode=disable password=lrwOuiz4gH
      - LOCKED_ADDR=0x533a245f03a1a46cacb933a3beef752fd8ff45c3
      - ERROR_THRESHOLD=0.1
      - WARNING_THRESHOLD=1
    links:
      - postgres

  webapp:
    build:
      context: ./horodateur_webapp
    ports:
      - "0.0.0.0:8001:8080"
    environment:
      - KEY_NAME=myservice # The .cert and .key must have the same name
      - IDP_METADATA=http://ec2-18-184-234-216.eu-central-1.compute.amazonaws.com/ssorec.geneveid.ch_dgsi_blockchain.xml #Public URL where IdP can be found
      - SP_URL=http://ec2-18-184-234-216.eu-central-1.compute.amazonaws.com:8001 # URL of the service provider
      - API_HOST=rcgech:8090 # API host, is equal to the <api container name>:<port>
    working_dir: /go/src/github.com/geneva_horodateur
    command: bash -c "go build -v -o /go/bin/main ./main.go && /go/bin/main"
    volumes:
      - "./myservice.cert:/go/src/github.com/geneva_horodateur/myservice.cert"
      - "./myservice.key:/go/src/github.com/geneva_horodateur/myservice.key"

  postgres:
    image: postgres:9.5
    environment:
      - POSTGRES_USER=tsUhfmkMfY
      - POSTGRES_PASSWORD=lrwOuiz4gH
      - POSTGRES_DB=rcgehorodatage

