version: '2'
services:
  rcgech:
    build: .
    environment:
      - WS_URI=https://rinkeby.infura.io/v3/afeacc980c634655875d915ed65cb0e4
      - PRIVATE_KEY=18030537DBDD38D0764947D40BED98FC4D2A21AF82765A7DE7B13D2E4076773C
      - DB_DSN=host=postgres user=tsUhfmkMfY dbname=rcgehorodatage sslmode=disable password=lrwOuiz4gH
      - LOCKED_ADDR=0x533a245f03a1a46cacb933a3beef752fd8ff45c3
      - ERROR_THRESHOLD=0.1
      - WARNING_THRESHOLD=1
    links:
      - postgres

  caddy-rev:
    image: abiosoft/caddy
    ports:
      - "0.0.0.0:8001:80"
      - "0.0.0.0:8443:443"
    volumes:
      - "./Caddyfile:/etc/Caddyfile:ro"
      - "./mockup:/var/www:ro"

  postgres:
    image: postgres:9.5
    environment:
      - POSTGRES_USER=tsUhfmkMfY
      - POSTGRES_PASSWORD=lrwOuiz4gH
      - POSTGRES_DB=rcgehorodatage
