version: '2'
services:
  rcgech:
    build: .
    ports:
      - "0.0.0.0:8090:8090"
    environment:
      - WS_URI=http://1.1.3.7:8545
      - PRIVATE_KEY=18030537dbdd38d0764947d40bed98fc4d2a21af82765a7de7b13d2e4076773c
      - DB_DSN=/tmp/sqlite.sql
  caddy-rev:
    image: abiosoft/caddy
    ports:
      - "0.0.0.0:8001:80"
      - "0.0.0.0:8443:443"
    volumes:
      - "./Caddyfile:/etc/Caddyfile:ro"
      - "./mockup:/var/www:ro"
